<li class="weapon">
  <label>Type (class name): </label><select class="weapon-class"></select> | 
  <label>Firing rate: </label><input class="rate" type="text" /> |
  <label>Firing direction: </label><select class="firing-type"><option selected=selected value="0">Static direction</option><option value="1">At player</option></select> | 
  <label>Static firing angle: </label><input class="firing-angle" type="text" />
  <button data-control="remove-weapon">Remove</button>
</li>